apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ya2mqtt
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}

