apiVersion: v1
kind: Service
metadata:
  name: {{ include "ChartName" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
      app: {{ include "ChartName" . }}
